version: '3'

services:
  database:
    image: postgres:14
    container_name: footballapi-database
    volumes:
      - /mnt/footballdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_OUTER_PORT}:${DATABASE_INNER_PORT}
    env_file:
      - .env

  server:
    image: golang:1.20-alpine
    container_name: footballapi-server
    working_dir: /app/src
    volumes:
    - ./:/app/src
    - apicompilecache:/go
    env_file:
      - .env
    ports:
    - ${SERVER_OUTER_PORT}:${SERVER_INNER_PORT}
    depends_on:
      - database
    entrypoint: "go run ./cmd/api"

  cache:
    image: redis:7-alpine
    container_name: footballapi-cache
    command: >
      --requirepass ${CACHE_PASSWORD}

  worker-competition:
    image: golang:1.20-alpine
    container_name: footballapi-worker-competition
    working_dir: /app/src
    restart: unless-stopped
    volumes:
    - ./:/app/src
    - apicompilecache:/go
    env_file:
      - .env
    depends_on:
      - database
      - broker
    entrypoint: "go run ./cmd/worker/competition"

  worker-team:
    image: golang:1.20-alpine
    container_name: footballapi-worker-team
    working_dir: /app/src
    restart: unless-stopped
    volumes:
      - ./:/app/src
      - apicompilecache:/go
    env_file:
      - .env
    depends_on:
      - database
      - broker
    entrypoint: "go run ./cmd/worker/team"

  worker-stats:
    image: golang:1.20-alpine
    container_name: footballapi-worker-stats
    working_dir: /app/src
    restart: unless-stopped
    volumes:
      - ./:/app/src
      - apicompilecache:/go
    env_file:
      - .env
    depends_on:
      - database
      - broker
    entrypoint: "go run ./cmd/worker/stats"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: footballapi-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: footballapi-broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'footballapi-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://footballapi-broker:9092,PLAINTEXT_INTERNAL://footballapi-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  apicompilecache:
