services:
  database:
    image: postgres:17
    container_name: footballapi-database
    volumes:
      - /mnt/footballdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_OUTER_PORT}:${DATABASE_INNER_PORT}
    env_file:
      - .env

  server:
    image: golang:1.22.11-alpine
    container_name: footballapi-server
    working_dir: /app/src
    volumes:
    - ./:/app/src
    - apicompilecache:/go
    env_file:
      - .env
    ports:
    - ${SERVER_OUTER_PORT}:${SERVER_INNER_PORT}
    depends_on:
      - database
    entrypoint: "go run ./cmd/api"

  cache:
    image: redis:7-alpine
    container_name: footballapi-cache
    command: >
      --requirepass ${CACHE_PASSWORD}

  worker-competition:
    image: golang:1.22.11-alpine
    container_name: footballapi-worker-competition
    working_dir: /app/src
    restart: unless-stopped
    volumes:
    - ./:/app/src
    - apicompilecache:/go
    env_file:
      - .env
    depends_on:
      - database
      - broker
    entrypoint: "go run ./cmd/worker/competition"

  worker-team:
    image: golang:1.22.11-alpine
    container_name: footballapi-worker-team
    working_dir: /app/src
    restart: unless-stopped
    volumes:
      - ./:/app/src
      - apicompilecache:/go
    env_file:
      - .env
    depends_on:
      - database
      - broker
    entrypoint: "go run ./cmd/worker/team"

  worker-stats:
    image: golang:1.22.11-alpine
    container_name: footballapi-worker-stats
    working_dir: /app/src
    restart: unless-stopped
    volumes:
      - ./:/app/src
      - apicompilecache:/go
    env_file:
      - .env
    depends_on:
      - database
      - broker
    entrypoint: "go run ./cmd/worker/stats"

  broker:
    image: bitnami/kafka:latest
    container_name: footballapi-broker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  apicompilecache:
