version: '3'

services:
  database:
    image: postgres:14
    container_name: footballapi-database
    volumes:
      - /mnt/footballdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_OUTER_PORT}:${DATABASE_INNER_PORT}
    env_file:
      - .env

  server:
    image: golang:1.20-alpine
    container_name: footballapi-server
    working_dir: /app/src
    volumes:
    - ./:/app/src
    - apicompilecache:/go
    env_file:
      - .env
    ports:
    - ${SERVER_OUTER_PORT}:${SERVER_INNER_PORT}
    depends_on:
      - database
    entrypoint: "go run ./cmd/api"

  cache:
    image: redis:7-alpine
    container_name: footballapi-cache
    command: >
      --requirepass ${CACHE_PASSWORD}

volumes:
  apicompilecache:
